# 3ยบ
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

# kubectl apply -f postgres-pvc.yaml

# kubectl get pv

# kubectl get pvc
