# 5ยบ
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: ClusterIP # NodePort
  ports:
    - port: 5432
  selector:
    app: postgres

# kubectl apply -f postgres-service.yaml

# kubectl get svc

# kubectl exec -it postgres-665b7554dc-cddgq -- psql -h localhost -U ps_user --password -p 5432 ps_db

